<?php
include_once("../base.php");
if(!empty($_FILES['img']['tmp_name'])){
  $_POST['img']="img/".$_FILES['img']['name'];
  move_uploaded_file($_FILES['img']['tmp_name'],$_POST['img']);
}
if(empty($_POST['seq'])){
  $_POST['seq']=rand(100000,999999);
}
$Goods->save($_POST);
to("../admin.php?do=ath");